<?xml version="1.0" encoding="UTF-8"?>
HTTP/1.1 200 OK
Server: GlassFish Server Open Source Edition  4.0.1 
Server: grizzly/2.3.11
Content-Type: text/xml;charset=utf-8
Date: Tue, 21 Oct 2014 18:46:03 GMT
Transfer-Encoding: chunked

<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.1-b259 (trunk-7770; 2013-10-30T04:04:22+0000) JAXWS-RI/2.2.9-b131029.1831 JAXWS-API/2.2.11 JAXB-RI/2.2.8-b131017.0915 JAXB-API/2.2.11 svn-revision#unknown. --><!-- Generated by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.1-b259 (trunk-7770; 2013-10-30T04:04:22+0000) JAXWS-RI/2.2.9-b131029.1831 JAXWS-API/2.2.11 JAXB-RI/2.2.8-b131017.0915 JAXB-API/2.2.11 svn-revision#unknown. --><definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao" name="NfeRetAutorizacao">
<types>
<xsd:schema>
<xsd:import namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao" schemaLocation="https://nfe.fazenda.ms.gov.br:443/producao/services2/NfeRetAutorizacao?xsd=1"/>
</xsd:schema>
</types>
<message name="nfeRetAutorizacaoLote">
<part name="nfeDadosMsg" element="tns:nfeDadosMsg"/>
<part name="nfeCabecMsg" element="tns:nfeCabecMsg"/>
</message>
<message name="nfeRetAutorizacaoLoteResponse">
<part name="nfeRetAutorizacaoLoteResult" element="tns:nfeRetAutorizacaoLoteResult"/>
<part name="nfeCabecMsg" element="tns:nfeCabecMsg"/>
</message>
<portType name="NfeRetAutorizacaoSoap">
<operation name="nfeRetAutorizacaoLote" parameterOrder="nfeDadosMsg nfeCabecMsg">
<input wsam:Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao/nfeRetAutorizacao" message="tns:nfeRetAutorizacaoLote"/>
<output wsam:Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao/NfeRetAutorizacaoSoap/nfeRetAutorizacaoLoteResponse" message="tns:nfeRetAutorizacaoLoteResponse"/>
</operation>
</portType>
<binding name="nfeRetAutorizacaoSoap12Binding" type="tns:NfeRetAutorizacaoSoap">
<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="nfeRetAutorizacaoLote">
<soap12:operation soapAction="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao/nfeRetAutorizacao"/>
<input>
<soap12:body use="literal" parts="nfeDadosMsg"/>
<soap12:header message="tns:nfeRetAutorizacaoLote" part="nfeCabecMsg" use="literal"/>
</input>
<output>
<soap12:body use="literal" parts="nfeRetAutorizacaoLoteResult"/>
<soap12:header message="tns:nfeRetAutorizacaoLoteResponse" part="nfeCabecMsg" use="literal"/>
</output>
</operation>
</binding>
<service name="NfeRetAutorizacao">
<port name="nfeRetAutorizacaoSoap12" binding="tns:nfeRetAutorizacaoSoap12Binding">
<soap12:address location="https://nfe.fazenda.ms.gov.br:443/producao/services2/NfeRetAutorizacao"/>
</port>
</service>
</definitions>